version: 2

updates:
  - package-ecosystem: pip
    directory: /sdk
    schedule:
      interval: weekly
    groups:
      pip-dependencies:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /server
    schedule:
      interval: weekly
    groups:
      pip-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /dashboard
    schedule:
      interval: weekly
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
